#!/usr/bin/env bash

. script/names.sh

JAR_DEPENDENCIES="${PACK_LIBS_FOLDERNAME}/${GUAVA_FILENAME}"
JAR_DEPENDENCIES="${JAR_DEPENDENCIES}:${PACK_LIBS_FOLDERNAME}/${JSR_FILENAME}"
JAR_DEPENDENCIES="${JAR_DEPENDENCIES}:${PACK_LIBS_FOLDERNAME}/${LOMBOK_FILENAME}"
JAR_DEPENDENCIES="${JAR_DEPENDENCIES}:${PACK_LIBS_FOLDERNAME}/${SLF4J_API_FILENAME}"
JAR_DEPENDENCIES="${JAR_DEPENDENCIES}:${PACK_LIBS_FOLDERNAME}/${COMMONS_CODEC_FILENAME}"
JAR_DEPENDENCIES="${JAR_DEPENDENCIES}:${PACK_LIBS_FOLDERNAME}/${COMMONS_LANG_FILENAME}"
JAR_DEPENDENCIES="${JAR_DEPENDENCIES}:${PACK_LIBS_FOLDERNAME}/${LOGBACK_CLASSIC_FILENAME}"
JAR_DEPENDENCIES="${JAR_DEPENDENCIES}:${PACK_LIBS_FOLDERNAME}/${LOGBACK_CORE_FILENAME}"

CLASSPATH="${PACK_APP_BIN_FOLDERNAME}/${APP_FOLDERNAME}:${JAR_DEPENDENCIES}"

java -cp ${CLASSPATH} ${MAIN_CLASS_FULLNAME}