#!/usr/bin/env bash

ROOT="/home/danilo/dev/projects/jdccget"
PACK_ROOT="/home/danilo/dev/projects/jdccget/deploy-package"
DEPLOY_ROOT_FOLDER="/home/pi/"

MAIN_CLASS_FULLNAME="jdcc.Main"
SCRIPT_FOLDERNAME="script"
NAMES_SCRIPT_FALENAME="names.sh"
RUN_SCRIPT_FILENAME="jdccget.sh"
APP_FOLDERNAME="jdccget"
CONFIG_FILENAME="config.txt"

APP_BIN_ROOT="${ROOT}/out/production"
LIBS_PATH="${ROOT}/3rd-libs"
SCRIPT_PATH="${ROOT}/${SCRIPT_FOLDERNAME}"

PACK_APP_BIN_FOLDERNAME="bin"
PACK_APP_BIN_ROOT="${PACK_ROOT}/${PACK_APP_BIN_FOLDERNAME}"
PACK_APP_BIN="${PACK_APP_BIN_ROOT}/${APP_FOLDERNAME}"
PACK_LIBS_FOLDERNAME="libs"
PACK_LIBS="${PACK_ROOT}/${PACK_LIBS_FOLDERNAME}"
PACK_SCRIPT_FOLDERNAME="${SCRIPT_FOLDERNAME}"
PACK_SCRIPT_PATH="${PACK_ROOT}/${PACK_SCRIPT_FOLDERNAME}"

DEPLOY_APP_FOLDERNAME="jdccget"
DEPLOY_APP_BACKUP_FOLDERNAME="jdccget.bak"
DEPLOY_APP_PATH="${DEPLOY_ROOT_FOLDER}/${DEPLOY_APP_FOLDERNAME}"
DEPLOY_APP_BACKUP_PATH="${DEPLOY_ROOT_FOLDER}/${DEPLOY_APP_BACKUP_FOLDERNAME}"
DEPLOY_REMOTE_USER="pi"
DEPLOY_REMOTE_PASSWORD="pi"
DEPLOY_REMOTE_HOST="pi2"

PIRCBOTX_DEPENDENCIES_PATH="${LIBS_PATH}/pircbotx/dependencies"
GUAVA_FILENAME="guava-21.0.jar"
JSR_FILENAME="jsr305-3.0.1.jar"
LOMBOK_FILENAME="lombok.jar"

SLF4J_PATH="${PIRCBOTX_DEPENDENCIES_PATH}/slf4j-1.7.25"
SLF4J_API_FILENAME="slf4j-api-1.7.25.jar"

COMMONS_LANG_PATH="${PIRCBOTX_DEPENDENCIES_PATH}/commons-lang3-3.5"
COMMONS_CODEC_PATH="${PIRCBOTX_DEPENDENCIES_PATH}/commons-codec-1.10"
COMMONS_CODEC_FILENAME="commons-codec-1.10.jar"
COMMONS_LANG_FILENAME="commons-lang3-3.5.jar"

LOGBACK_PATH="${LIBS_PATH}/logback-1.2.3"
LOGBACK_CLASSIC_FILENAME="logback-classic-1.2.3.jar"
LOGBACK_CORE_FILENAME="logback-core-1.2.3.jar"